// <auto-generated />
using System;
using FlowBill.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowBill.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105184823_AddProductCategories")]
    partial class AddProductCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowBill.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BTWBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BestelDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("BestelNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotaal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Totaal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("FlowBill.Models.BestellingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("BTWPercentage")
                        .HasColumnType("int");

                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrijsPerStuk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Totaal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("ProductId");

                    b.ToTable("BestellingItems");
                });

            modelBuilder.Entity("FlowBill.Models.Factuur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BTWBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<bool>("EmailVerzonden")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailVerzondenOp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FactuurDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactuurNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDFPad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotaal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Totaal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VervalDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId")
                        .IsUnique();

                    b.ToTable("Facturen");
                });

            modelBuilder.Entity("FlowBill.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTWNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bedrijfsnaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contactpersoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KVKNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Voorbeeldstraat 1",
                            BTWNummer = "NL123456789B01",
                            Bedrijfsnaam = "Voorbeeld Bedrijf B.V.",
                            Contactpersoon = "Jan Jansen",
                            Email = "info@voorbeeld.nl",
                            KVKNummer = "12345678",
                            Postcode = "1234 AB",
                            Stad = "Amsterdam",
                            Telefoon = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            AangemaaktOp = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Innovatielaan 45",
                            BTWNummer = "NL987654321B02",
                            Bedrijfsnaam = "TechSolutions Nederland",
                            Contactpersoon = "Sophie de Vries",
                            Email = "sophie@techsolutions.nl",
                            KVKNummer = "87654321",
                            Postcode = "3045 BC",
                            Stad = "Rotterdam",
                            Telefoon = "0687654321"
                        });
                });

            modelBuilder.Entity("FlowBill.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<int>("BTWPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Voorraad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Producten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 1,
                            IsActief = true,
                            Naam = "Website ontwikkeling",
                            Omschrijving = "Complete website ontwikkeling op maat",
                            Prijs = 2500.00m,
                            SKU = "WEB001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 2,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 1,
                            IsActief = true,
                            Naam = "Hosting - Jaarlijks",
                            Omschrijving = "Betrouwbare webhosting voor 1 jaar",
                            Prijs = 120.00m,
                            SKU = "HOST001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 3,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 1,
                            IsActief = true,
                            Naam = "SEO Optimalisatie",
                            Omschrijving = "Zoekmotor optimalisatie voor betere vindbaarheid",
                            Prijs = 750.00m,
                            SKU = "SEO001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 4,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 1,
                            IsActief = true,
                            Naam = "Logo ontwerp",
                            Omschrijving = "Professioneel logo ontwerp inclusief 3 concepten",
                            Prijs = 350.00m,
                            SKU = "LOGO001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 5,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 2,
                            IsActief = true,
                            Naam = "The Last of Us Part II",
                            Omschrijving = "Spannend actie-avonturen game voor PlayStation 5",
                            Prijs = 59.99m,
                            SKU = "GAME001",
                            Voorraad = 45
                        },
                        new
                        {
                            Id = 6,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 2,
                            IsActief = true,
                            Naam = "FIFA 25",
                            Omschrijving = "De nieuwste voetbalsimulatie game",
                            Prijs = 69.99m,
                            SKU = "GAME002",
                            Voorraad = 60
                        },
                        new
                        {
                            Id = 7,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 2,
                            IsActief = true,
                            Naam = "Red Dead Redemption 2",
                            Omschrijving = "Western actie-avontuur game voor meerdere platforms",
                            Prijs = 49.99m,
                            SKU = "GAME003",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 8,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 2,
                            IsActief = true,
                            Naam = "Mario Kart 8 Deluxe",
                            Omschrijving = "Populaire racegame voor Nintendo Switch",
                            Prijs = 54.99m,
                            SKU = "GAME004",
                            Voorraad = 50
                        },
                        new
                        {
                            Id = 9,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 3,
                            IsActief = true,
                            Naam = "Yoga Mat Premium",
                            Omschrijving = "Extra dikke yogamat met anti-slip oppervlak (6mm)",
                            Prijs = 29.99m,
                            SKU = "SPORT001",
                            Voorraad = 75
                        },
                        new
                        {
                            Id = 10,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 3,
                            IsActief = true,
                            Naam = "Dumbbells Set 2x10kg",
                            Omschrijving = "Verstelbare dumbbells set voor thuisfitness",
                            Prijs = 89.99m,
                            SKU = "SPORT002",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 11,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 3,
                            IsActief = true,
                            Naam = "Hardloopschoenen Pro",
                            Omschrijving = "Professionele hardloopschoenen met extra demping",
                            Prijs = 129.99m,
                            SKU = "SPORT003",
                            Voorraad = 55
                        },
                        new
                        {
                            Id = 12,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            CategoryId = 3,
                            IsActief = true,
                            Naam = "Fitness Tracker Smart",
                            Omschrijving = "Slimme fitness tracker met hartslagmeter en GPS",
                            Prijs = 79.99m,
                            SKU = "SPORT004",
                            Voorraad = 65
                        });
                });

            modelBuilder.Entity("FlowBill.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconClass = "fas fa-globe",
                            IsActief = true,
                            Naam = "Webdiensten",
                            Omschrijving = "Professionele webdiensten en online oplossingen"
                        },
                        new
                        {
                            Id = 2,
                            IconClass = "fas fa-gamepad",
                            IsActief = true,
                            Naam = "Games",
                            Omschrijving = "Populaire videogames voor verschillende platforms"
                        },
                        new
                        {
                            Id = 3,
                            IconClass = "fas fa-dumbbell",
                            IsActief = true,
                            Naam = "Sport",
                            Omschrijving = "Sportartikelen en fitnessequipment"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlowBill.Models.Bestelling", b =>
                {
                    b.HasOne("FlowBill.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("FlowBill.Models.BestellingItem", b =>
                {
                    b.HasOne("FlowBill.Models.Bestelling", "Bestelling")
                        .WithMany("BestellingItems")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowBill.Models.Product", "Product")
                        .WithMany("BestellingItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FlowBill.Models.Factuur", b =>
                {
                    b.HasOne("FlowBill.Models.Bestelling", "Bestelling")
                        .WithOne("Factuur")
                        .HasForeignKey("FlowBill.Models.Factuur", "BestellingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");
                });

            modelBuilder.Entity("FlowBill.Models.Product", b =>
                {
                    b.HasOne("FlowBill.Models.ProductCategory", "Category")
                        .WithMany("Producten")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowBill.Models.Bestelling", b =>
                {
                    b.Navigation("BestellingItems");

                    b.Navigation("Factuur");
                });

            modelBuilder.Entity("FlowBill.Models.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("FlowBill.Models.Product", b =>
                {
                    b.Navigation("BestellingItems");
                });

            modelBuilder.Entity("FlowBill.Models.ProductCategory", b =>
                {
                    b.Navigation("Producten");
                });
#pragma warning restore 612, 618
        }
    }
}
