// <auto-generated />
using System;
using FlowBill.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowBill.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023214356_Add9ExtraCustomers")]
    partial class Add9ExtraCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowBill.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BTWBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BestelDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("BestelNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotaal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Totaal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("FlowBill.Models.BestellingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("BTWPercentage")
                        .HasColumnType("int");

                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrijsPerStuk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Totaal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("ProductId");

                    b.ToTable("BestellingItems");
                });

            modelBuilder.Entity("FlowBill.Models.Factuur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BTWBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<bool>("EmailVerzonden")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailVerzondenOp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FactuurDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactuurNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDFPad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotaal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Totaal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VervalDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId")
                        .IsUnique();

                    b.ToTable("Facturen");
                });

            modelBuilder.Entity("FlowBill.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTWNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bedrijfsnaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contactpersoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KVKNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Voorbeeldstraat 1",
                            BTWNummer = "NL123456789B01",
                            Bedrijfsnaam = "Voorbeeld Bedrijf B.V.",
                            Contactpersoon = "Jan Jansen",
                            Email = "info@voorbeeld.nl",
                            KVKNummer = "12345678",
                            Postcode = "1234 AB",
                            Stad = "Amsterdam",
                            Telefoon = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            AangemaaktOp = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Innovatielaan 45",
                            BTWNummer = "NL987654321B02",
                            Bedrijfsnaam = "TechSolutions Nederland",
                            Contactpersoon = "Sophie de Vries",
                            Email = "sophie@techsolutions.nl",
                            KVKNummer = "87654321",
                            Postcode = "3045 BC",
                            Stad = "Rotterdam",
                            Telefoon = "0687654321"
                        },
                        new
                        {
                            Id = 3,
                            AangemaaktOp = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Marktplein 12",
                            BTWNummer = "NL234567890B03",
                            Bedrijfsnaam = "Bakkerij Van Dam",
                            Contactpersoon = "Pieter van Dam",
                            Email = "pieter@bakkerijvandam.nl",
                            KVKNummer = "23456789",
                            Postcode = "4567 CD",
                            Stad = "Utrecht",
                            Telefoon = "0623456789"
                        },
                        new
                        {
                            Id = 4,
                            AangemaaktOp = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Duurzaamweg 78",
                            BTWNummer = "NL345678901B04",
                            Bedrijfsnaam = "Green Energy Solutions",
                            Contactpersoon = "Emma Mulder",
                            Email = "emma@greenenergy.nl",
                            KVKNummer = "34567890",
                            Postcode = "2345 DE",
                            Stad = "Den Haag",
                            Telefoon = "0634567890"
                        },
                        new
                        {
                            Id = 5,
                            AangemaaktOp = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Businesspark 100",
                            BTWNummer = "NL456789012B05",
                            Bedrijfsnaam = "Consultancy Partners",
                            Contactpersoon = "Marco Visser",
                            Email = "marco@consultancy.nl",
                            KVKNummer = "45678901",
                            Postcode = "5678 EF",
                            Stad = "Eindhoven",
                            Telefoon = "0645678901"
                        },
                        new
                        {
                            Id = 6,
                            AangemaaktOp = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Designstraat 23",
                            BTWNummer = "NL567890123B06",
                            Bedrijfsnaam = "Creative Media Group",
                            Contactpersoon = "Lisa Bakker",
                            Email = "lisa@creativemedia.nl",
                            KVKNummer = "56789012",
                            Postcode = "6789 FG",
                            Stad = "Groningen",
                            Telefoon = "0656789012"
                        },
                        new
                        {
                            Id = 7,
                            AangemaaktOp = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Kraanweg 56",
                            BTWNummer = "NL678901234B07",
                            Bedrijfsnaam = "Bouwbedrijf Hendriks",
                            Contactpersoon = "Tom Hendriks",
                            Email = "tom@bouwbedrijf.nl",
                            KVKNummer = "67890123",
                            Postcode = "7890 GH",
                            Stad = "Breda",
                            Telefoon = "0667890123"
                        },
                        new
                        {
                            Id = 8,
                            AangemaaktOp = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Marktstraat 8",
                            BTWNummer = "NL789012345B08",
                            Bedrijfsnaam = "Restaurant De Gouden Lepel",
                            Contactpersoon = "Anna de Wit",
                            Email = "anna@goudenlepel.nl",
                            KVKNummer = "78901234",
                            Postcode = "8901 HI",
                            Stad = "Maastricht",
                            Telefoon = "0678901234"
                        },
                        new
                        {
                            Id = 9,
                            AangemaaktOp = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Sportlaan 99",
                            BTWNummer = "NL890123456B09",
                            Bedrijfsnaam = "Fitness First Nederland",
                            Contactpersoon = "David Peters",
                            Email = "david@fitnessfirst.nl",
                            KVKNummer = "89012345",
                            Postcode = "9012 IJ",
                            Stad = "Nijmegen",
                            Telefoon = "0689012345"
                        },
                        new
                        {
                            Id = 10,
                            AangemaaktOp = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adres = "Digitalweg 200",
                            BTWNummer = "NL901234567B10",
                            Bedrijfsnaam = "Online Marketing Pro",
                            Contactpersoon = "Sarah van Leeuwen",
                            Email = "sarah@onlinemarketing.nl",
                            KVKNummer = "90123456",
                            Postcode = "1012 JK",
                            Stad = "Amsterdam",
                            Telefoon = "0690123456"
                        });
                });

            modelBuilder.Entity("FlowBill.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<int>("BTWPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActief")
                        .HasColumnType("bit");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Voorraad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Producten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Website ontwikkeling",
                            Omschrijving = "Complete website ontwikkeling",
                            Prijs = 2500.00m,
                            SKU = "WEB001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 2,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Hosting - Jaarlijks",
                            Omschrijving = "Webhosting voor 1 jaar",
                            Prijs = 120.00m,
                            SKU = "HOST001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 3,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "SEO Optimalisatie",
                            Omschrijving = "Zoekmotor optimalisatie",
                            Prijs = 750.00m,
                            SKU = "SEO001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 4,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Logo ontwerp",
                            Omschrijving = "Professioneel logo ontwerp",
                            Prijs = 350.00m,
                            SKU = "LOGO001",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 5,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "The Last of Us Part II",
                            Omschrijving = "Spannend actie-avonturen game voor PlayStation 5",
                            Prijs = 59.99m,
                            SKU = "GAME001",
                            Voorraad = 45
                        },
                        new
                        {
                            Id = 6,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "FIFA 25",
                            Omschrijving = "Populaire voetbalsimulatie game",
                            Prijs = 69.99m,
                            SKU = "GAME002",
                            Voorraad = 60
                        },
                        new
                        {
                            Id = 7,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Minecraft",
                            Omschrijving = "Sandbox bouw- en survival game",
                            Prijs = 29.99m,
                            SKU = "GAME003",
                            Voorraad = 120
                        },
                        new
                        {
                            Id = 8,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Call of Duty: Modern Warfare III",
                            Omschrijving = "Eerste persoons shooter game",
                            Prijs = 69.99m,
                            SKU = "GAME004",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 9,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Zelda: Tears of the Kingdom",
                            Omschrijving = "Avonturen game voor Nintendo Switch",
                            Prijs = 59.99m,
                            SKU = "GAME005",
                            Voorraad = 50
                        },
                        new
                        {
                            Id = 10,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "God of War Ragnarök",
                            Omschrijving = "Mythologische actie-avonturen game",
                            Prijs = 59.99m,
                            SKU = "GAME006",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 11,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Mario Kart 8 Deluxe",
                            Omschrijving = "Racing game voor Nintendo Switch",
                            Prijs = 49.99m,
                            SKU = "GAME007",
                            Voorraad = 75
                        },
                        new
                        {
                            Id = 12,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Elden Ring",
                            Omschrijving = "Action RPG game",
                            Prijs = 49.99m,
                            SKU = "GAME008",
                            Voorraad = 55
                        },
                        new
                        {
                            Id = 13,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "iPhone 15 Pro Max 256GB",
                            Omschrijving = "Premium smartphone van Apple",
                            Prijs = 1349.00m,
                            SKU = "GSM001",
                            Voorraad = 25
                        },
                        new
                        {
                            Id = 14,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Samsung Galaxy S24 Ultra 512GB",
                            Omschrijving = "Krachtige Android smartphone",
                            Prijs = 1299.00m,
                            SKU = "GSM002",
                            Voorraad = 30
                        },
                        new
                        {
                            Id = 15,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Google Pixel 8 Pro 128GB",
                            Omschrijving = "Smartphone met pure Android ervaring",
                            Prijs = 899.00m,
                            SKU = "GSM003",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 16,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "OnePlus 12 256GB",
                            Omschrijving = "Snelle en betaalbare flagship smartphone",
                            Prijs = 799.00m,
                            SKU = "GSM004",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 17,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "iPhone 14 128GB",
                            Omschrijving = "Vorige generatie iPhone, nog steeds populair",
                            Prijs = 799.00m,
                            SKU = "GSM005",
                            Voorraad = 50
                        },
                        new
                        {
                            Id = 18,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Xiaomi 14 Pro 256GB",
                            Omschrijving = "Betaalbare smartphone met goede specs",
                            Prijs = 649.00m,
                            SKU = "GSM006",
                            Voorraad = 45
                        },
                        new
                        {
                            Id = 19,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Samsung Galaxy A54 128GB",
                            Omschrijving = "Mid-range smartphone met goede features",
                            Prijs = 449.00m,
                            SKU = "GSM007",
                            Voorraad = 60
                        },
                        new
                        {
                            Id = 20,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "Atomic Habits - James Clear",
                            Omschrijving = "Bestseller over het opbouwen van goede gewoonten",
                            Prijs = 24.99m,
                            SKU = "BOOK001",
                            Voorraad = 80
                        },
                        new
                        {
                            Id = 21,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "Het Diner - Herman Koch",
                            Omschrijving = "Nederlandse thriller roman",
                            Prijs = 19.99m,
                            SKU = "BOOK002",
                            Voorraad = 65
                        },
                        new
                        {
                            Id = 22,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "Sapiens - Yuval Noah Harari",
                            Omschrijving = "Geschiedenis van de mensheid",
                            Prijs = 29.99m,
                            SKU = "BOOK003",
                            Voorraad = 70
                        },
                        new
                        {
                            Id = 23,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "De Meeste Mensen Deugen - Rutger Bregman",
                            Omschrijving = "Optimistisch perspectief op de mensheid",
                            Prijs = 22.99m,
                            SKU = "BOOK004",
                            Voorraad = 55
                        },
                        new
                        {
                            Id = 24,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "1984 - George Orwell",
                            Omschrijving = "Klassieke dystopische roman",
                            Prijs = 14.99m,
                            SKU = "BOOK005",
                            Voorraad = 90
                        },
                        new
                        {
                            Id = 25,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "Clean Code - Robert Martin",
                            Omschrijving = "Programmeerboek over code kwaliteit",
                            Prijs = 49.99m,
                            SKU = "BOOK006",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 26,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "Harry Potter - Volledige set",
                            Omschrijving = "Complete Harry Potter boekenreeks",
                            Prijs = 89.99m,
                            SKU = "BOOK007",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 27,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 9,
                            IsActief = true,
                            Naam = "De Alchemist - Paulo Coelho",
                            Omschrijving = "Inspirerende roman over zelfontdekking",
                            Prijs = 19.99m,
                            SKU = "BOOK008",
                            Voorraad = 60
                        },
                        new
                        {
                            Id = 28,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "MacBook Pro 14 inch M3 Pro",
                            Omschrijving = "Professionele laptop voor creators",
                            Prijs = 2399.00m,
                            SKU = "COMP001",
                            Voorraad = 20
                        },
                        new
                        {
                            Id = 29,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Dell XPS 15",
                            Omschrijving = "Krachtige Windows laptop",
                            Prijs = 1799.00m,
                            SKU = "COMP002",
                            Voorraad = 25
                        },
                        new
                        {
                            Id = 30,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Lenovo ThinkPad X1 Carbon",
                            Omschrijving = "Business laptop met lange batterijduur",
                            Prijs = 1599.00m,
                            SKU = "COMP003",
                            Voorraad = 30
                        },
                        new
                        {
                            Id = 31,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "ASUS ROG Strix Gaming Laptop",
                            Omschrijving = "Gaming laptop met RTX 4070",
                            Prijs = 1899.00m,
                            SKU = "COMP004",
                            Voorraad = 18
                        },
                        new
                        {
                            Id = 32,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "HP Pavilion 15",
                            Omschrijving = "Betaalbare laptop voor dagelijks gebruik",
                            Prijs = 699.00m,
                            SKU = "COMP005",
                            Voorraad = 45
                        },
                        new
                        {
                            Id = 33,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Sony WH-1000XM5",
                            Omschrijving = "Premium noise-cancelling headphones",
                            Prijs = 379.00m,
                            SKU = "AUDIO001",
                            Voorraad = 50
                        },
                        new
                        {
                            Id = 34,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Apple AirPods Pro (2e generatie)",
                            Omschrijving = "Draadloze oordopjes met ANC",
                            Prijs = 279.00m,
                            SKU = "AUDIO002",
                            Voorraad = 65
                        },
                        new
                        {
                            Id = 35,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Bose QuietComfort 45",
                            Omschrijving = "Comfortabele noise-cancelling headphones",
                            Prijs = 329.00m,
                            SKU = "AUDIO003",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 36,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "JBL Flip 6",
                            Omschrijving = "Draagbare Bluetooth speaker",
                            Prijs = 129.00m,
                            SKU = "AUDIO004",
                            Voorraad = 75
                        },
                        new
                        {
                            Id = 37,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Sonos One SL",
                            Omschrijving = "Smart speaker voor thuis",
                            Prijs = 199.00m,
                            SKU = "AUDIO005",
                            Voorraad = 55
                        },
                        new
                        {
                            Id = 38,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "iPad Pro 12.9 inch 256GB",
                            Omschrijving = "Professionele tablet met M2 chip",
                            Prijs = 1349.00m,
                            SKU = "TAB001",
                            Voorraad = 30
                        },
                        new
                        {
                            Id = 39,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Samsung Galaxy Tab S9",
                            Omschrijving = "Premium Android tablet",
                            Prijs = 899.00m,
                            SKU = "TAB002",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 40,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "iPad Air 10.9 inch 128GB",
                            Omschrijving = "Veelzijdige tablet voor werk en vrije tijd",
                            Prijs = 699.00m,
                            SKU = "TAB003",
                            Voorraad = 45
                        },
                        new
                        {
                            Id = 41,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Amazon Fire HD 10",
                            Omschrijving = "Betaalbare tablet voor entertainment",
                            Prijs = 159.00m,
                            SKU = "TAB004",
                            Voorraad = 70
                        },
                        new
                        {
                            Id = 42,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Apple Watch Series 9",
                            Omschrijving = "Smartwatch met gezondheidsmonitoring",
                            Prijs = 449.00m,
                            SKU = "WATCH001",
                            Voorraad = 55
                        },
                        new
                        {
                            Id = 43,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Samsung Galaxy Watch 6",
                            Omschrijving = "Android smartwatch met vele functies",
                            Prijs = 329.00m,
                            SKU = "WATCH002",
                            Voorraad = 60
                        },
                        new
                        {
                            Id = 44,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Garmin Forerunner 265",
                            Omschrijving = "Sporthorloge voor hardlopers",
                            Prijs = 449.00m,
                            SKU = "WATCH003",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 45,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Fitbit Charge 6",
                            Omschrijving = "Fitness tracker met hartslagmeter",
                            Prijs = 159.00m,
                            SKU = "WATCH004",
                            Voorraad = 80
                        },
                        new
                        {
                            Id = 46,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Sony A7 IV",
                            Omschrijving = "Full-frame mirrorless camera",
                            Prijs = 2699.00m,
                            SKU = "CAM001",
                            Voorraad = 15
                        },
                        new
                        {
                            Id = 47,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Canon EOS R6 Mark II",
                            Omschrijving = "Veelzijdige full-frame camera",
                            Prijs = 2499.00m,
                            SKU = "CAM002",
                            Voorraad = 18
                        },
                        new
                        {
                            Id = 48,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "DJI Mini 4 Pro",
                            Omschrijving = "Compacte drone met 4K camera",
                            Prijs = 759.00m,
                            SKU = "CAM003",
                            Voorraad = 30
                        },
                        new
                        {
                            Id = 49,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "GoPro Hero 12 Black",
                            Omschrijving = "Actiecamera voor extreme sporten",
                            Prijs = 449.00m,
                            SKU = "CAM004",
                            Voorraad = 50
                        },
                        new
                        {
                            Id = 50,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "LG UltraGear 27 inch 4K Gaming Monitor",
                            Omschrijving = "Gaming monitor met hoge refresh rate",
                            Prijs = 699.00m,
                            SKU = "MON001",
                            Voorraad = 25
                        },
                        new
                        {
                            Id = 51,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Dell UltraSharp 32 inch 4K Monitor",
                            Omschrijving = "Professioneel beeldscherm voor werk",
                            Prijs = 849.00m,
                            SKU = "MON002",
                            Voorraad = 30
                        },
                        new
                        {
                            Id = 52,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Samsung Odyssey G7",
                            Omschrijving = "Curved gaming monitor",
                            Prijs = 599.00m,
                            SKU = "MON003",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 53,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "PlayStation 5",
                            Omschrijving = "Next-gen gaming console",
                            Prijs = 549.00m,
                            SKU = "CONS001",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 54,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Xbox Series X",
                            Omschrijving = "Krachtige gaming console van Microsoft",
                            Prijs = 499.00m,
                            SKU = "CONS002",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 55,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Nintendo Switch OLED",
                            Omschrijving = "Hybride gaming console",
                            Prijs = 349.00m,
                            SKU = "CONS003",
                            Voorraad = 50
                        },
                        new
                        {
                            Id = 56,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "PlayStation VR2",
                            Omschrijving = "Virtual reality headset voor PS5",
                            Prijs = 549.00m,
                            SKU = "CONS004",
                            Voorraad = 20
                        },
                        new
                        {
                            Id = 57,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Xbox Elite Controller Series 2",
                            Omschrijving = "Premium gaming controller",
                            Prijs = 179.00m,
                            SKU = "CONS005",
                            Voorraad = 45
                        },
                        new
                        {
                            Id = 58,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Microsoft Office 365 Personal - 1 jaar",
                            Omschrijving = "Productiviteitssoftware abonnement",
                            Prijs = 69.00m,
                            SKU = "SOFT001",
                            Voorraad = 200
                        },
                        new
                        {
                            Id = 59,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Adobe Creative Cloud - 1 jaar",
                            Omschrijving = "Complete suite voor creatieven",
                            Prijs = 719.00m,
                            SKU = "SOFT002",
                            Voorraad = 150
                        },
                        new
                        {
                            Id = 60,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Norton 360 Deluxe - 1 jaar",
                            Omschrijving = "Antivirus en beveiligingssoftware",
                            Prijs = 39.99m,
                            SKU = "SOFT003",
                            Voorraad = 180
                        },
                        new
                        {
                            Id = 61,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Logitech MX Master 3S",
                            Omschrijving = "Draadloze premium muis",
                            Prijs = 109.00m,
                            SKU = "ACC001",
                            Voorraad = 70
                        },
                        new
                        {
                            Id = 62,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Keychron K8 Pro Mechanical Keyboard",
                            Omschrijving = "Draadloos mechanisch toetsenbord",
                            Prijs = 119.00m,
                            SKU = "ACC002",
                            Voorraad = 55
                        },
                        new
                        {
                            Id = 63,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Anker PowerCore 20000mAh",
                            Omschrijving = "Draagbare powerbank",
                            Prijs = 49.99m,
                            SKU = "ACC003",
                            Voorraad = 90
                        },
                        new
                        {
                            Id = 64,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "SanDisk Extreme Pro 1TB SSD",
                            Omschrijving = "Externe SSD voor opslag",
                            Prijs = 149.00m,
                            SKU = "ACC004",
                            Voorraad = 60
                        },
                        new
                        {
                            Id = 65,
                            AangemaaktOp = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BTWPercentage = 21,
                            IsActief = true,
                            Naam = "Webcam Logitech C920",
                            Omschrijving = "Full HD webcam voor videobellen",
                            Prijs = 79.00m,
                            SKU = "ACC005",
                            Voorraad = 65
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlowBill.Models.Bestelling", b =>
                {
                    b.HasOne("FlowBill.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("FlowBill.Models.BestellingItem", b =>
                {
                    b.HasOne("FlowBill.Models.Bestelling", "Bestelling")
                        .WithMany("BestellingItems")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowBill.Models.Product", "Product")
                        .WithMany("BestellingItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FlowBill.Models.Factuur", b =>
                {
                    b.HasOne("FlowBill.Models.Bestelling", "Bestelling")
                        .WithOne("Factuur")
                        .HasForeignKey("FlowBill.Models.Factuur", "BestellingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowBill.Models.Bestelling", b =>
                {
                    b.Navigation("BestellingItems");

                    b.Navigation("Factuur");
                });

            modelBuilder.Entity("FlowBill.Models.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("FlowBill.Models.Product", b =>
                {
                    b.Navigation("BestellingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
